
source_files =  [
	"cailie.cpp",
	"process.cpp",
	"thread.cpp",
	"messages.cpp",
	"listener.cpp",
	"net.cpp",
	"output.cpp",
	"packing.cpp",
	"listener.cpp",
	"tracelog.cpp",
	"utils.cpp",
]

Export("source_files")

SConscript('SConscript', variant_dir='build', src='.', duplicate=0)
SConscript('SConscript-mpi', variant_dir='build-mpi', src='.', duplicate=0)

Default("build")
