source_files = (
    "analyses.cpp",
    "statespace.cpp"
)

def build(ctx):
    if not ctx.env.HAVE_VERIF:
        return
    ctx.stlib(source=source_files,
              target="caverif",
              includes="../cailie",
              name="caverif")
