
main: main.cpp
	g++ -o main main.cpp -I../../../libs/cailie -L../../../build/libs/cailie -L. -lparameters -lcailie -lpthread -lrt -g

main_mpi: main.cpp
	mpic++ main.cpp -o main_mpi -I../../../libs/cailie -L../../../build/libs/cailie -L. -lparameters_mpi -lcailiempi -lpthread -lrt

clean:
	rm -f main main_mpi
