
source_files = Split("cailie.cpp unit.cpp path.cpp process.cpp messages.cpp output.cpp listener.cpp packing.cpp logging.cpp")

Export("source_files")

SConscript('SConscript', variant_dir='build', src='.', duplicate=0)
SConscript('SConscript-mpi', variant_dir='build-mpi', src='.', duplicate=0)

Default("build")
