#!/usr/bin/env python
import sys
import traceback
import argparse
import ConfigParser

import base.paths

config = ConfigParser.RawConfigParser()
if not config.read(base.paths.KAIRA_CONFIG_INI):
    print "File '{0}' was not found.".format(
        base.paths.KAIRA_CONFIG_INI)
    print "See 'docs/userguide.txt' the for installation instructions."
    sys.exit(1)

import base.project as project
from base.utils import PtpException
import gencpp.targetenv

debug_mode = False

target_envs = {
    "C++" : gencpp.targetenv.CppTargetEnv(),
}

def get_config(section, name):
    try:
        return config.get(section, name)
    except ConfigParser.NoOptionError:
        raise PtpException("{0}/{1} not found in config.ini\n"
                           "It means that Kaira is not properly configured\n"
                           "Run './waf configure' in Kaira top directory".format(section, name))

def get_generator_from_xml(element):
    return project.load_project(element, target_envs).get_generator()

def main():
    parser = argparse.ArgumentParser(description="PTP - ProjectToProgram compiler")
    parser.add_argument("operation",
                        metavar="OPERATION",
                        type=str,
                        help="Possible values: build, statespace,"
                             "place-user-fn, transition-user-fn")
    parser.add_argument("project",
                        metavar="FILENAME",
                        type=str,
                        help="path to XML file generated by GUI")
    parser.add_argument("--debug",
                        action='store_true',
                        help="Run PTP in debug mode")
    parser.add_argument("--output",
                        metavar="DIRECTORY",
                        type=str,
                        help="Directory where output files are generated")
    args = parser.parse_args()

    if args.debug:
        global debug_mode
        debug_mode = True

    if args.output is None:
        output_directory = "."
    else:
        output_directory = args.output

    p = project.load_project_from_file(args.project, target_envs, args.operation)
    generator = p.get_generator()

    if args.operation == "build":
        generator.build(output_directory)
    elif args.operation == "statespace":
        generator.build_statespace(output_directory)
    elif args.operation == "simrun":
        generator.build_simrun(output_directory)
    elif args.operation == "lib":
        generator.build_lib(output_directory)
    else:
        raise PtpException("Unknown operation")

if __name__ == '__main__':
    try:
        main()
    except PtpException, e:
        print e
        if debug_mode:
            traceback.print_exc(file=sys.stdout)
        sys.exit(1)
