
def build(ctx):
    if ctx.env.HAVE_DOC:
        ctx(rule="${ASCIIDOC} "
                 "-b html5 -a toc2 -a theme=volnitsky "
                 "-o ${TGT} ${SRC[0].abspath()}",
            source="userguide.txt",
            target="userguide.html")

        ctx(rule="${ASCIIDOC} "
                 "-b html5 -a toc2 -a theme=volnitsky -a data-uri "
                 "-o ${TGT} ${SRC[0].abspath()} ",
            source="extensions.txt",
            target="extensions.html")
